//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio5_1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShoeInventoryDBEntities : DbContext
    {
        public ShoeInventoryDBEntities()
            : base("name=ShoeInventoryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ShoeInventoryTable> ShoeInventoryTables { get; set; }

        public System.Data.Entity.DbSet<Portfolio5_1.Models.ClassListView> ClassListViews { get; set; }
    }
}
