//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio5_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoeInventoryTable
    {
        public int Id { get; set; }
        public string ShoeName { get; set; }
        public string ShoeDescription { get; set; }
        public string ShoePrice { get; set; }
        public Nullable<int> ShoeSize { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
